[activate]
other = "Activate sensor"

[active]
other = "Active"

[addthing]
other = "Add new thing"

[alerts]
other = "Alerts"

[all]
other = "All"

[area]
other = "Area"

[batterylevel]
other = "Battery level"

[cancel]
other = "Cancel"

[choose]
other = "Choose"

[chooseMeasurementtype]
other = "Pick measurement type"

[currentlevel]
other = "Current level"

[delete]
other = "Delete"

[description]
other = "Description"

[details]
other = "Details"

[deveui]
other = "DevEUI"

[edit]
other = "Edit"

[fillinglevel]
other = "Filling level"

[functions]
other = "Functions"

[graph]
other = "Graph"

[home]
other = "Home"

[id]
other = "ID"

[inactive]
other = "Inactive"

[lastseen]
other = "Last seen"

[latitude]
other = "Latitude"

[lifebuoy]
other = "Lifebuoy"

[list]
other = "List"

[location]
other = "Location"

[login]
other = "Log in"

[logout]
other = "Log out"

[longitude]
other = "Longitude"

[manyactive]
other = "Active"

[manyinactive]
other = "Inactive"

[map]
other = "Map"

[measurementtype]
other = "Measurement type"

[measurementvalue]
other = "Measurement value"

[measurementvalues]
other = "Measurement values"

[name]
other = "Name"

[notloggedin]
other = "Please log in"

[organisation]
other = "Organisation"

[overview]
other = "Overview"

[pickOption]
other = "Pick an option"

[rowsPerPage]
other = "Rows per page"

[save]
other = "Save"

[search]
other = "Search"

[selectedfilters]
other = "Selected filters:"

[sensorconnected]
other = "Connected sensor"

[sensormissing]
other = "Sensor missing"

[sensors]
other = "Sensors"

[sensortype]
other = "Type of sensor"

[status]
other = "Status"

[statistics]
other = "Statistics"

[table]
other = "Table"

[temperature]
other = "Temperature"

[thingtype]
other = "Type of thing"

[things]
other = "Things"

[time]
other = "Time"

[timeinterval]
other = "Time interval"

[total]
other = "Total"

[trashcan]
other = "Trashcan"

[type]
other = "Type"

[unregistered]
other = "Unregistered"

[3-9]
other = "Battery level (%)"

[3-7]
other = "Battery level (mV)"

[3303-5700]
other = "Temperature"

[3424-1]
other = "Cumulated water consumption"

[3435-1]
other = "Container height"

[3435-2]
other = "Actual filling percentage"

[3435-3]
other = "Actual filling level"

[3304-5700]
other = "Relative humidity"

[3200-5501]
other = "Digital input counter"

[3428-17]
other = "Carbon dioxide"

[3350-5544]
other = "Cumulative time"

[3330-5700]
other = "Distance"

[3331-5700]
other = "Cumulated energy consumption"