[activate]
other = "Activate sensor"

[active]
other = "Active"

[addthing]
other = "Add new thing"

[alerts]
other = "Alerts"

[area]
other = "Area"

[batterylevel]
other = "Battery level"

[cancel]
other = "Cancel"

[choose]
other = "Choose"

[chooseMeasurementtype]
other = "Pick measurement type"

[delete]
other = "Delete"

[description]
other = "Description"

[details]
other = "Details"

[deveui]
other = "DevEUI"

[edit]
other = "Edit"

[fillinglevel]
other = "Filling level"

[functions]
other = "Functions"

[home]
other = "Home"

[id]
other = "ID"

[inactive]
other = "Inactive"

[lastseen]
other = "Last seen"

[latitude]
other = "Latitude"

[list]
other = "List"

[location]
other = "Location"

[logout]
other = "Log out"

[longitude]
other = "Longitude"

[manyactive]
other = "Active"

[manyinactive]
other = "Inactive"

[map]
other = "Map"

[measurementtype]
other = "Measurement type"

[measurementvalue]
other = "Measurement value"

[measurementvalues]
other = "Measurement values"

[name]
other = "Name"

[organisation]
other = "Organisation"

[overview]
other = "Overview"

[pickOption]
other = "Pick an option"

[save]
other = "Save"

[search]
other = "Search"

[sensors]
other = "Sensors"

[sensortype]
other = "Type of sensor"

[status]
other = "Status"

[thingtype]
other = "Type of thing"

[things]
other = "Things"

[time]
other = "Time"

[total]
other = "Total"

[type]
other = "Type"

[unregistered]
other = "Unregistered"