[30]
other = ">30%"

[50]
other = ">50%"

[activate]
other = "Activate sensor"

[active]
other = "Active"

[activesensors]
other = "Active sensors"

[add]
other = "Add"

[addthing]
other = "Add new thing"

[addtag]
other = "Add new tag"

[admin]
other = "Admin"

[air]
other = "Air"

[alerts]
other = "Alerts"

[all]
other = "All"

[alternativeName]
other = "Alternative name"

[angle]
other = "Angle"

[angleis]
other = "The angle is"

[angleismissing]
other = "Angle missing."

[area]
other = "Area"

[batterylevel]
other = "Battery level"

[PointOfInterest-Beach]
other = "Beach"

[Beach]
other = "Beach"

[Building]
other = "Building"

[cancel]
other = "Cancel"

[category]
other = "Category"

[choose]
other = "Choose"

[chooseMeasurementtype]
other = "Pick measurement type"

[choosetags]
other = "Choose tags"

[consumption]
other = "Consumption"

[container]
other = "Container"

[containerheight]
other = "The container has a height of"

[cumulativevolume]
other = "Cumulative volume"

[currentlevel]
other = "Current level"

[currenttemperature]
other = "Current temperature"

[degrees]
other = "degrees"

[delete]
other = "Delete"

[deletethingconfirm]
other = "Do you want to delete"

[deletethinginformation]
other = "and data related to the thing will be removed."

[description]
other = "Description"

[Desk]
other = "Desk"

[desk]
other = "Desk"

[details]
other = "Details"

[deveui]
other = "DevEUI"

[edit]
other = "Edit"

[endtime]
other = "End time"

[export]
other = "Export"

[fillinglevel]
other = "Filling level"

[functions]
other = "Functions"

[graph]
other = "Graph"

[home]
other = "Home"

[id]
other = "ID"

[import]
other = "Import"

[inactive]
other = "Inactive"

[inactivesensors]
other = "Inactive sensors"

[information]
other = "Information"

[present]
other = "Present"

[lastseen]
other = "Last seen"

[latitude]
other = "Latitude"

[level]
other = "Level"

[lifebuoy]
other = "Lifebuoy"

[Lifebuoy]
other = "Lifebuoy"

[list]
other = "List"

[location]
other = "Location"

[login]
other = "Log in"

[logout]
other = "Log out"

[longitude]
other = "Longitude"

[manyactive]
other = "Active"

[manyinactive]
other = "Inactive"

[map]
other = "Map"

[maxfillingheight]
other = "with a maximum filling height of"

[maxfillinglevel]
other = "Max filling level"

[maxcontainerheight]
other = "Container height"

[maxdistancesewer]
other = "Distance sensor to bottom"

[maxlevel]
other = "Max filling height"

[maxwaterlevel]
other = "Max water level"

[maxwaterlevelheight]
other = "Max water level is"

[measurements]
other = "Measurements"

[measurementperday]
other = "Measurements per day"

[measurementtype]
other = "Measurement type"

[measurementvalue]
other = "Measurement value"

[measurementvalues]
other = "Measurement values"

[missing]
other = "Missing"

[missingdata]
other = "Missing data"

[missingpage]
other = "Page is missing"

[mm]
other = "mm"

[more]
other = "more"

[moreinformation]
other = "More information"

[name]
other = "Name"

[no]
other = "No"

[nodata]
other = "-"

[notloggedin]
other = "Please log in"

[notPresent]
other = "Not present"

[numberofpassages]
other = "Number of passages"

[numberofpassagestoday]
other = "Number of passages today"

[numberofsensors]
other = "Number of sensors"

[off]
other = "Off"

[offline]
other = "Offline"

[offset]
other = "Offset"

[offsetsetting]
other = "with an offset set to"

[online]
other = "Online"

[oops]
other = "Oops..."

[organisation]
other = "Organisation"

[overflow]
other = "Overflow"

[overflowrightnow]
other = "Overflow right now"

[overview]
other = "Overview"

[Passage]
other = "Passage"

[pickOption]
other = "Pick an option"

[picksensor]
other = "Pick sensor"

[placement]
other = "Placement"

[PointOfInterest]
other = "Point of interest"

[pointoftime]
other = "Time"

[pumping]
other = "Pumping"

[Pumpingstation]
other = "Pumping station"

[PumpingStation]
other = "Pumping station"

[room]
other = "Room"

[Room]
other = "Room"

[rowsPerPage]
other = "Rows per page"

[Container-Sandstorage]
other = "Sand storage"

[sandstorage]
other = "Sand storage"

[Sandstorage]
other = "Sand storage"

[save]
other = "Save"

[search]
other = "Search"

[selectedfilters]
other = "Selected filters:"

[sensorconnected]
other = "Connected sensor"

[sensorID]
other = "Sensor ID"

[sensormissing]
other = "Sensor missing"

[sensors]
other = "Sensors"

[sensortype]
other = "Type of sensor"

[sensorsof]
other = "sensors out of"

[sewerheight]
other = "Distance from sensor to bottom is"

[show]
other = "Showing"

[size]
other = "Size"

[soil]
other = "Soil"

[starttime]
other = "Start time"

[status]
other = "Status"

[statistics]
other = "Statistics"

[table]
other = "Table"

[tags]
other = "Tags"

[temperature]
other = "Temperature"

[thingtype]
other = "Type of thing"

[things]
other = "Things"

[thingsof]
other = "things out of"

[time]
other = "Time"

[timeinterval]
other = "Time interval"

[total]
other = "Total"

[totaltime]
other = "Total time"

[type]
other = "Type"

[unknown]
other = "Unknown"

[unknownsensors]
other = "Unknown sensors"

[water]
other = "Water"

[WaterMeter]
other = "Water meter"

[yes]
other = "Yes"

[10351-50]
other = "Number of passages"

[3-9]
other = "Battery level (%)"

[3-7]
other = "Battery level (mV)"

[3303-5700]
other = "Temperature"

[3424-1]
other = "Cumulated water consumption"

[3434-1]
other = "Actual number of persons"

[3434-2]	
other = "Daily number of persons"

[3435-1]
other = "Container height"

[3435-2]
other = "Actual filling percentage"

[3435-3]
other = "Actual filling level"

[3304-5700]
other = "Relative humidity"

[3200-5500]
other = "Digital Input State"

[3200-5501]
other = "Digital input counter"

[3428-17]
other = "Carbon dioxide"

[3350-5544]
other = "Cumulative time"

[3330-5700]
other = "Distance"

[3331-5700]
other = "Cumulated energy consumption"

[oma-lwm2m-ext-3]
other = "Device"

[oma-lwm2m-ext-3200]
other = "Digital input"

[oma-lwm2m-ext-3301]
other = "Illuminance"

[oma-lwm2m-ext-3302]
other = "Presence"

[oma-lwm2m-ext-3303]
other = "Temperature"

[oma-lwm2m-ext-3304]
other = "Humidity"

[oma-lwm2m-ext-3323]
other = "Pressure"

[oma-lwm2m-ext-3327]
other = "Conductivity"

[oma-lwm2m-ext-3328]
other = "Power"

[oma-lwm2m-ext-3330]
other = "Distance"

[oma-lwm2m-ext-3331]
other = "Energy consumption"

[oma-lwm2m-ext-3350]
other = "Timing"

[oma-lwm2m-ext-3411]
other = "Battery"

[oma-lwm2m-ext-3424]
other = "Water meter"

[oma-lwm2m-ext-3428]
other = "Air quality"

[oma-lwm2m-ext-3434]
other = "People counter"

[oma-lwm2m-ext-3435]
other = "Filling level"

[Sewer-CombinedSewerOverflow]
other = "Combined sewer overflow"

[CombinedSewerOverflow]
other = "Combined sewer overflow"

[combinedseweroverflow]
other = "Combined sewer overflow"

[passage]
other = "Passage"

[sewagepumpingstation]
other = "Sewage pumping station"

[Sewer]
other = "Sewer"

[sewer]
other = "Sewer"

[Container-WasteContainer]
other = "Waste container"

[WasteContainer]
other = "Waste container"

[wastecontainer]
other = "Waste container"

[choosefile]
other = "Choose a file"

[upload]
other = "Upload"