[activate]
other = "Activate sensor"

[active]
other = "Active"

[activesensors]
other = "Active sensors"

[add]
other = "Add"

[addthing]
other = "Add new thing"

[addtag]
other = "Add new tag"

[alerts]
other = "Alerts"

[all]
other = "All"

[area]
other = "Area"

[batterylevel]
other = "Battery level"

[cancel]
other = "Cancel"

[choose]
other = "Choose"

[chooseMeasurementtype]
other = "Pick measurement type"

[choosetags]
other = "Choose tags"

[currentlevel]
other = "Current level"

[delete]
other = "Delete"

[description]
other = "Description"

[details]
other = "Details"

[deveui]
other = "DevEUI"

[edit]
other = "Edit"

[endtime]
other = "End time"

[fillinglevel]
other = "Filling level"

[functions]
other = "Functions"

[graph]
other = "Graph"

[home]
other = "Home"

[id]
other = "ID"

[inactive]
other = "Inactive"

[inactivesensors]
other = "Inactive sensors"

[information]
other = "Information"

[lastseen]
other = "Last seen"

[latitude]
other = "Latitude"

[lifebuoy]
other = "Lifebuoy"

[list]
other = "List"

[location]
other = "Location"

[login]
other = "Log in"

[logout]
other = "Log out"

[longitude]
other = "Longitude"

[manyactive]
other = "Active"

[manyinactive]
other = "Inactive"

[map]
other = "Map"

[measurementperday]
other = "Measurements per day"

[measurementtype]
other = "Measurement type"

[measurementvalue]
other = "Measurement value"

[measurementvalues]
other = "Measurement values"

[missing]
other = "Missing"

[moreinformation]
other = "More information"

[more]
other = "more"

[name]
other = "Name"

[no]
other = "No"

[notloggedin]
other = "Please log in"

[numberofpassages]
other = "Number of passages"

[numberofpassagestoday]
other = "Number of passages today"

[numberofsensors]
other = "Number of sensors"

[offline]
other = "Offline"

[online]
other = "Online"

[organisation]
other = "Organisation"

[overflow]
other = "Overflow"

[overflowrightnow]
other = "Overflow right now"

[overview]
other = "Overview"

[pickOption]
other = "Pick an option"

[picksensor]
other = "Pick sensor"

[rowsPerPage]
other = "Rows per page"

[save]
other = "Save"

[search]
other = "Search"

[selectedfilters]
other = "Selected filters:"

[sensorconnected]
other = "Connected sensor"

[sensormissing]
other = "Sensor missing"

[sensors]
other = "Sensors"

[sensortype]
other = "Type of sensor"

[starttime]
other = "Start time"

[status]
other = "Status"

[statistics]
other = "Statistics"

[table]
other = "Table"

[tags]
other = "Tags"

[temperature]
other = "Temperature"

[thingtype]
other = "Type of thing"

[things]
other = "Things"

[time]
other = "Time"

[timeinterval]
other = "Time interval"

[total]
other = "Total"

[totaltime]
other = "Total time"

[trashcan]
other = "Trashcan"

[type]
other = "Type"

[unknown]
other = "Unknown"

[unknownsensors]
other = "Unknown sensors"

[yes]
other = "Yes"

[3-9]
other = "Battery level (%)"

[3-7]
other = "Battery level (mV)"

[3303-5700]
other = "Temperature"

[3424-1]
other = "Cumulated water consumption"

[3434-1]
other = "Actual number of persons"

[3434-2]	
other = "Daily number of persons"

[3435-1]
other = "Container height"

[3435-2]
other = "Actual filling percentage"

[3435-3]
other = "Actual filling level"

[3304-5700]
other = "Relative humidity"

[3200-5500]
other = "Digital Input State"

[3200-5501]
other = "Digital input counter"

[3428-17]
other = "Carbon dioxide"

[3350-5544]
other = "Cumulative time"

[3330-5700]
other = "Distance"

[3331-5700]
other = "Cumulated energy consumption"

[CombinedSewageOverflow]
other = "Combined sewage overflow"

[combinedsewageoverflow]
other = "Combined sewage overflow"

[passage]
other = "Passage"

[sewagepumpingstation]
other = "Sewage pumping station"

[Sewer]
other = "Sewer"

[sewer]
other = "Sewer"

[WasteContainer]
other = "Waste container"

[wastecontainer]
other = "Waste container"

[noData]
other = "-"