[overview]
other = "Overview"

[home]
other = "Home"

[sensors]
other = "Sensors"

[things]
other = "Things"

[functions]
other = "Functions"

[name]
other = "Name"

[search]
other = "Search"

[status]
other = "Status"

[deveui]
other = "DevEUI"

[batterylevel]
other = "Battery level"

[lastseen]
other = "Last seen"

[alerts]
other = "Alerts"

[total]
other = "Total"

[manyactive]
other = "Active"

[manyinactive]
other = "Inactive"

[active]
other = "Active"

[inactive]
other = "Inactive"

[unregistered]
other = "Unregistered"

[thingtype]
other = "Type of thing"

[sensortype]
other = "Type of sensor"

[measurementtype]
other = "Measurement type"

[chooseMeasurementtype]
other = "Pick measurement type"

[choose]
other = "Choose"

[edit]
other = "Edit"

[description]
other = "Description"

[organisation]
other = "Organisation"

[time]
other = "Time"

[type]
other = "Type"

[location]
other = "Location"

[latitude]
other = "Latitude"

[longitude]
other = "Longitude"

[details]
other = "Details"

[activate]
other = "Activate sensor"

[delete]
other = "Delete"

[cancel]
other = "Cancel"

[save]
other = "Save"

[logout]
other = "Log out"

[fillinglevel]
other = "Filling level"

[area]
other = "Area"

[addthing]
other = "Add new thing"

[pickOption]
other = "Pick an option"