[overview]
other = "Overview"

[home]
other = "Home"

[sensors]
other = "Sensors"

[objects]
other = "Objects"

[functions]
other = "Functions"

[name]
other = "Name"

[status]
other = "Status"

[deveui]
other = "DevEUI"

[batterylevel]
other = "Battery level"

[lastseen]
other = "Last seen"

[alerts]
other = "Alerts"

[total]
other = "Total"

[active]
other = "Active"

[inactive]
other = "Inactive"

[unregistered]
other = "Unregistered"

[sensortype]
other = "Type of sensor"

[measurementtype]
other = "Measurement type"