[activate]
other = "Aktivera sensor"

[active]
other = "Aktiv"

[addthing]
other = "Lägg till ny sak"

[alerts]
other = "Larm"

[all]
other = "Alla"

[area]
other = "Område"

[batterylevel]
other = "Batterinivå"

[cancel]
other = "Avbryt"

[choose]
other = "Välj"

[chooseMeasurementtype]
other = "Ange mättyp"

[currentlevel]
other = "Aktuell nivå"

[delete]
other = "Radera"

[description]
other = "Beskrivning"

[details]
other = "Uppgifter"

[deveui]
other = "DevEUI"

[edit]
other = "Redigera"

[endtime]
other = "Sluttid"

[fillinglevel]
other = "Fyllnadsnivå"

[functions]
other = "Funktioner"

[graph]
other = "Graf"

[home]
other = "Hem"

[id]
other = "ID"

[inactive]
other = "Inaktiv"

[lastseen]
other = "Senast sedd"

[list]
other = "Lista"

[latitude]
other = "Latitud"

[lifebuoy]
other = "Livboj"

[location]
other = "Position"

[login]
other = "Logga in"

[logout]
other = "Logga ut"

[longitude]
other = "Longitud"

[manyactive]
other = "Aktiva"

[manyinactive]
other = "Inaktiva"

[map]
other = "Karta"

[measurementtype]
other = "Mättyp"

[measurementvalue]
other = "Mätvärde"

[measurementvalues]
other = "Mätvärden"

[name]
other = "Namn"

[notloggedin]
other = "Du behöver logga in"

[numberofpassages]
other = "Antal passager"

[numberofpassagestoday]
other = "Antal passager idag"

[organisation]
other = "Organisation"

[overflowrightnow]
other = "Bräddar just nu"

[overview]
other = "Översikt"

[pickOption]
other = "Välj ett alternativ"

[rowsPerPage]
other = "Rader per sida"

[save]
other = "Spara"

[search]
other = "Sök"

[selectedfilters]
other = "Valda filter:"

[sensorconnected]
other = "Kopplad sensor"

[sensormissing]
other = "Sensor saknas"

[sensors]
other = "Sensorer"

[sensortype]
other = "Sensortyp"

[starttime]
other = "Starttid"

[status]
other = "Status"

[statistics]
other = "Statistik"

[table]
other = "Tabell"

[temperature]
other = "Temperatur"

[thingtype]
other = "Typ av sak"

[things]
other = "Saker"

[time]
other = "Tid"

[timeinterval]
other = "Tidsintervall"

[total]
other = "Totalt"

[totaltime]
other = "Total tid"

[trashcan]
other = "Soptunna"

[type]
other = "Typ"

[unregistered]
other = "Oregistrerade"

[3-9]
other = "Batterinivå (%)"

[3-7]
other = "Batterinivå (mV)"

[3303-5700]
other = "Temperatur"

[3424-1]
other = "Total vattenförbrukning"

[3435-1]
other = "Höjd"

[3435-2]
other = "Fyllnadsnivå (%)"

[3435-3]
other = "Fyllnadsnivå (cm)"

[3304-5700]
other = "Luftfuktighet"

[3200-5501]
other = "Digital räknare"

[3428-17]
other = "Koldioxid"

[3350-5544]
other = "Total tid"

[3330-5700]
other = "Distans"

[3331-5700]
other = "Total energiförbrukning"

[CombinedSewageOverflow]
other = "Avlopp som svämmar över"

[combinedsewageoverflow]
other = "Avlopp som svämmar över"

[sewagepumpingstation]
other = "Pumpstation avloppsvatten"

[Sewer]
other = "Avlopp"

[sewer]
other = "Avlopp"

[WasteContainer]
other = "Soptunna"

[wastecontainer]
other = "Soptunna"