[activate]
other = "Aktivera sensor"

[active]
other = "Aktiv"

[addthing]
other = "Lägg till ny sak"

[alerts]
other = "Larm"

[area]
other = "Område"

[batterylevel]
other = "Batterinivå"

[cancel]
other = "Avbryt"

[choose]
other = "Välj"

[chooseMeasurementtype]
other = "Ange mättyp"

[delete]
other = "Radera"

[description]
other = "Beskrivning"

[details]
other = "Uppgifter"

[deveui]
other = "DevEUI"

[edit]
other = "Redigera"

[fillinglevel]
other = "Fyllnadsnivå"

[functions]
other = "Funktioner"

[home]
other = "Hem"

[id]
other = "ID"

[inactive]
other = "Inaktiv"

[lastseen]
other = "Senast sedd"

[latitude]
other = "Latitud"

[location]
other = "Position"

[logout]
other = "Logga ut"

[longitude]
other = "Longitud"

[manyactive]
other = "Aktiva"

[manyinactive]
other = "Inaktiva"

[measurementtype]
other = "Mättyp"

[measurementvalue]
other = "Mätvärde"

[measurementvalues]
other = "Mätvärden"

[name]
other = "Namn"

[organisation]
other = "Organisation"

[overview]
other = "Översikt"

[pickOption]
other = "Välj ett alternativ"

[save]
other = "Spara"

[search]
other = "Sök"

[sensors]
other = "Sensorer"

[sensortype]
other = "Sensortyp"

[status]
other = "Status"

[thingtype]
other = "Typ av sak"

[things]
other = "Saker"

[time]
other = "Starttid"

[total]
other = "Totalt"

[type]
other = "Typ"

[unregistered]
other = "Oregistrerade"