[overview]
other = "Översikt"

[home]
other = "Hem"

[sensors]
other = "Sensorer"

[objects]
other = "Saker"

[functions]
other = "Funktioner"

[name]
other = "Namn"

[status]
other = "Status"

[deveui]
other = "DevEUI"

[batterylevel]
other = "Batterinivå"

[lastseen]
other = "Senast sedd"

[alerts]
other = "Larm"

[total]
other = "Totalt"

[active]
other = "Aktiva"

[inactive]
other = "Inaktiva"

[unregistered]
other = "Oregistrerade"

[sensortype]
other = "Sensortyp"

[measurementtype]
other = "Mättyp"