[30]
other = ">30%"

[50]
other = ">50%"

[activate]
other = "Aktivera sensor"

[active]
other = "Aktiv"

[activesensors]
other = "Aktiva sensorer"

[add]
other = "Lägg till"

[addthing]
other = "Lägg till ny sak"

[addtag]
other = "Lägg till ny tagg"

[alerts]
other = "Larm"

[all]
other = "Alla"

[alternativeName]
other = "Alternativt namn"

[angle]
other = "Vinkel"

[angleis]
other = "Vinkeln är"

[angleismissing]
other = "Vinkel saknas."

[area]
other = "Område"

[batterylevel]
other = "Batterinivå"

[PointOfInterest-Beach]
other = "Strand"

[Beach]
other = "Strand"

[Building]
other = "Byggnad"

[cancel]
other = "Avbryt"

[category]
other = "Kategori"

[choose]
other = "Välj"

[chooseMeasurementtype]
other = "Ange mättyp"

[choosetags]
other = "Välj taggar"

[consumption]
other = "Förbrukning"

[container]
other = "Välj taggar"

[containerheight]
other = "Behållaren har en höjd på"

[cumulativevolume]
other = "Ackumulerad volym"

[currentlevel]
other = "Aktuell nivå"

[currenttemperature]
other = "Nuvarande temperatur"

[degrees]
other = "grader"

[delete]
other = "Radera"

[deletethingconfirm]
other = "Vill du radera"

[deletethinginformation]
other = "och dess data kommer tas bort."

[description]
other = "Beskrivning"

[desk]
other = "Skrivbord"

[details]
other = "Uppgifter"

[deveui]
other = "DevEUI"

[edit]
other = "Redigera"

[endtime]
other = "Sluttid"

[export]
other = "Exportera"

[fillinglevel]
other = "Fyllnadsnivå"

[functions]
other = "Funktioner"

[graph]
other = "Graf"

[home]
other = "Hem"

[id]
other = "ID"

[import]
other = "Importera"

[inactive]
other = "Inaktiv"

[inactivesensors]
other = "Inaktiva sensorer"

[information]
other = "Information"

[inplace]
other = "På plats"

[lastseen]
other = "Senast sedd"

[level]
other = "Nivå"

[list]
other = "Lista"

[latitude]
other = "Latitud"

[lifebuoy]
other = "Livboj"

[Lifebuoy]
other = "Livboj"

[location]
other = "Position"

[login]
other = "Logga in"

[logout]
other = "Logga ut"

[longitude]
other = "Longitud"

[manyactive]
other = "Aktiva"

[manyinactive]
other = "Inaktiva"

[map]
other = "Karta"

[maxfillingheight]
other = "med en max fyllnadshöjd på"

[maxheight]
other = "Behållarens höjd"

[maxlevel]
other = "Max fyllnadshöjd"

[measurementperday]
other = "Antal mätvärden per dag"

[measurementtype]
other = "Mättyp"

[measurementvalue]
other = "Mätvärde"

[measurementvalues]
other = "Mätvärden"

[missing]
other = "Saknas"

[missingdata]
other = "Data saknas"

[missingpage]
other = "Sida saknas"

[mm]
other = "mm"

[more]
other = "till"

[moreinformation]
other = "Mer information"

[name]
other = "Namn"

[no]
other = "Nej"

[nodata]
other = "-"

[notloggedin]
other = "Du behöver logga in"

[notPresent]
other = "Saknas"

[numberofpassages]
other = "Antal passager"

[numberofpassagestoday]
other = "Antal passager idag"

[numberofsensors]
other = "Antal sensorer"

[off]
other = "Av"

[offline]
other = "Offline"

[online]
other = "Online"

[oops]
other = "Oops..."

[organisation]
other = "Organisation"

[overflow]
other = "Bräddar"

[overflowrightnow]
other = "Bräddar just nu"

[overview]
other = "Översikt"

[Passage]
other = "Passage"

[pickOption]
other = "Välj ett alternativ"

[picksensor]
other = "Välj sensor"

[PointOfInterest]
other = "Intressepunkt"

[pointoftime]
other = "Tidpunkt"

[pumping]
other = "Pumpar"

[Pumpingstation]
other = "Pumpstation"

[PumpingStation]
other = "Pumpstation"

[room]
other = "Rum"

[Room]
other = "Rum"

[rowsPerPage]
other = "Rader per sida"

[Container-Sandstorage]
other = "Sandficka"

[sandstorage]
other = "Sandficka"

[Sandstorage]
other = "Sandficka"

[save]
other = "Spara"

[search]
other = "Sök"

[selectedfilters]
other = "Valda filter:"

[sensorconnected]
other = "Kopplad sensor"

[sensorID]
other = "Sensor ID"

[sensormissing]
other = "Sensor saknas"

[sensors]
other = "Sensorer"

[sensortype]
other = "Sensortyp"

[sensorsof]
other = "sensorer av"

[show]
other = "Visar"

[size]
other = "Storlek"

[starttime]
other = "Starttid"

[status]
other = "Status"

[statistics]
other = "Statistik"

[table]
other = "Tabell"

[tags]
other = "Taggar"

[temperature]
other = "Temperatur"

[thingtype]
other = "Typ av sak"

[things]
other = "Saker"

[thingsof]
other = "saker av"

[time]
other = "Tid"

[timeinterval]
other = "Tidsintervall"

[total]
other = "Totalt"

[totaltime]
other = "Total tid"

[type]
other = "Typ"

[unknown]
other = "Okänd"

[unknownsensors]
other = "Okända sensorer"

[WaterMeter]
other = "Vattenmätare"

[yes]
other = "Ja"

[10351-50]
other = "Antal passager"

[3-9]
other = "Batterinivå (%)"

[3-7]
other = "Batterinivå (mV)"

[3303-5700]
other = "Temperatur"

[3424-1]
other = "Total vattenförbrukning"

[3434-1]
other = "Antal personer"

[3434-2]	
other = "Antal personer per dag"

[3435-1]
other = "Höjd"

[3435-2]
other = "Fyllnadsnivå (%)"

[3435-3]
other = "Fyllnadsnivå (cm)"

[3304-5700]
other = "Luftfuktighet"

[3200-5500]
other = "Digital Input State"

[3200-5501]
other = "Digital räknare"

[3428-17]
other = "Koldioxid"

[3350-5544]
other = "Total tid"

[3330-5700]
other = "Distans"

[3331-5700]
other = "Total energiförbrukning"

[oma-lwm2m-ext-3]
other = "Sensor"

[oma-lwm2m-ext-3200]
other = "Digital ingång"

[oma-lwm2m-ext-3301]
other = "Belysningsstyrka"

[oma-lwm2m-ext-3302]
other = "Närvaro"

[oma-lwm2m-ext-3303]
other = "Temperatur"

[oma-lwm2m-ext-3304]
other = "Luftfuktighet"

[oma-lwm2m-ext-3323]
other = "Tryck"

[oma-lwm2m-ext-3327]
other = "Ledningsförmåga"

[oma-lwm2m-ext-3328]
other = "Effekt"

[oma-lwm2m-ext-3330]
other = "Distans"

[oma-lwm2m-ext-3331]
other = "Energiförbrukning"

[oma-lwm2m-ext-3350]
other = "Tidtagning"

[oma-lwm2m-ext-3411]
other = "Batteri"

[oma-lwm2m-ext-3424]
other = "Vattenmätning"

[oma-lwm2m-ext-3428]
other = "Luftkvalitet"

[oma-lwm2m-ext-3434]
other = "Personräknare"

[oma-lwm2m-ext-3435]
other = "Fyllnadsnivå"

[Sewer-CombinedSewerOverflow]
other = "Bräddavlopp"

[CombinedSewerOverflow]
other = "Bräddavlopp"

[combinedseweroverflow]
other = "Bräddavlopp"

[passage]
other = "Passage"

[sewagepumpingstation]
other = "Pumpstation"

[Sewer]
other = "Avlopp"

[sewer]
other = "Avlopp"

[Container-WasteContainer]
other = "Soptunna"

[WasteContainer]
other = "Soptunna"

[wastecontainer]
other = "Soptunna"